// src/pages/store/checkout/checkoutStyles.js

export const S = {
  page: { padding: 16, maxWidth: 1100, margin: "0 auto", width: "100%", boxSizing: "border-box" },
  grid: { display: "grid", gridTemplateColumns: "minmax(0, 1.4fr) minmax(300px, 0.9fr)", gap: 16, alignItems: "start" },
  card: { background: "#fff", border: "1px solid #eee", borderRadius: 14, padding: 14, boxSizing: "border-box", width: "100%" },
  h1: { margin: 0, fontSize: 22, fontWeight: 900 },
  muted: { color: "#666", fontSize: 13 },
  row: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)", gap: 12 },
  mobileRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr)", gap: 10 },
  twoCol: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) minmax(0, 1fr)", gap: 10 },
  field: { display: "grid", gap: 6, minWidth: 0 },
  label: { fontSize: 12, color: "#555", fontWeight: 700 },
  input: { border: "1px solid #ddd", borderRadius: 12, padding: "10px 12px", outline: "none", fontSize: 14, width: "100%", boxSizing: "border-box" },
  inputError: { borderColor: "#f87171", borderWidth: 1.5 },
  btn: (variant = "primary", disabled = false) => ({
    width: "100%",
    borderRadius: 12,
    padding: "12px 14px",
    fontWeight: 900,
    cursor: disabled ? "not-allowed" : "pointer",
    border: variant === "primary" ? "1px solid #0f766e" : "1px solid #ddd",
    background: variant === "primary" ? (disabled ? "#9ca3af" : "#0f766e") : "#fff",
    color: variant === "primary" ? "#fff" : "#111",
    opacity: disabled ? 0.85 : 1,
  }),
  stepPill: (active) => ({
    padding: "8px 10px",
    borderRadius: 999,
    border: active ? "1px solid #0f766e" : "1px solid #ddd",
    background: active ? "#e0f2f1" : "#fff",
    fontSize: 12,
    fontWeight: 900,
    color: "#111",
  }),
  link: {
    border: "none",
    background: "transparent",
    color: "#0f766e",
    fontWeight: 900,
    cursor: "pointer",
    padding: 0,
    textDecoration: "underline",
  },
  miniBtn: {
    border: "1px solid #ddd",
    background: "#fff",
    borderRadius: 10,
    width: 34,
    height: 34,
    cursor: "pointer",
  },
  greenText: { fontSize: 12, color: "#0f766e", fontWeight: 900 },
};
